### ISSUE TITLE
PostgreSQL data directory was initialized by a different version

### ISSUE THREAD

**Issue by ersel** [MaxWaldorf/guacamole#2]
Thanks for sharing this container image. I am running into a postgres issue when trying to run this as part of a docker-compose script:

```
version: "2"
services:
  ubuntu-instance:
    image: danielguerra/ubuntu-xrdp:20.04
    container_name: docker-ubuntu-instance
    environment:
      - shm-size=1g
      - hostname=terminalserver
    ports:
      - "2222:22"
      - 3389:3389
  guacamole-instance:
    image: maxwaldorf/guacamole
    container_name: docker-guacamole-instance
    volumes:
        - ~/guacamole-conf:/config
        - db:/var/lib/postgresql/data
    ports:
        - 8080:8080
volumes:
  db:
```

Here is the error message I am getting
```
docker-guacamole-instance | 2021-04-10 15:45:46.296 UTC [321] FATAL:  database files are incompatible with server
docker-guacamole-instance | 2021-04-10 15:45:46.296 UTC [321] DETAIL:  The data directory was initialized by PostgreSQL version 9.6, which is not compatible with this version 11.10 (Debian 11.10-0+deb10u1).
```

Any ideas why this might be happening?
